# Generated by Django 2.2.1 on 2019-05-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('id_next', models.IntegerField(blank=True, null=True)),
                ('id_prev', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='MoocCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course')),
            ],
            options={
                'db_table': 'mooc_course',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissions_link', models.TextField(blank=True, null=True)),
                ('programs_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('semester', models.SmallIntegerField(blank=True, null=True)),
                ('id_course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course')),
            ],
            options={
                'db_table': 'school_course',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('id_mooc_course', models.ForeignKey(db_column='id_mooc_course', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.MoocCourse')),
            ],
            options={
                'db_table': 'week',
            },
        ),
        migrations.CreateModel(
            name='ACategoryCourse',
            fields=[
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='courses.Category')),
            ],
            options={
                'db_table': 'a_category_course',
            },
        ),
        migrations.CreateModel(
            name='ACourseInstructor',
            fields=[
                ('id_course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='courses.Course')),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Instructor')),
            ],
            options={
                'db_table': 'a_course_instructor',
                'unique_together': {('id_course', 'id_instructor')},
            },
        ),
        migrations.CreateModel(
            name='ACourseResource',
            fields=[
                ('id_resource', models.ForeignKey(db_column='id_resource', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='courses.Resource')),
            ],
            options={
                'db_table': 'a_course_resource',
            },
        ),
        migrations.CreateModel(
            name='ASchoolCourseItem',
            fields=[
                ('id_school_course', models.ForeignKey(db_column='id_school_course', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='courses.SchoolCourse')),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Item')),
            ],
            options={
                'db_table': 'a_school_course_item',
                'unique_together': {('id_school_course', 'id_item')},
            },
        ),
        migrations.CreateModel(
            name='AWeekItem',
            fields=[
                ('id_week', models.ForeignKey(db_column='id_week', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='courses.Week')),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Item')),
            ],
            options={
                'db_table': 'a_week_item',
                'unique_together': {('id_week', 'id_item')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Item')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='NonSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Instructor')),
            ],
            options={
                'db_table': 'non_school',
            },
        ),
        migrations.AddField(
            model_name='week',
            name='items',
            field=models.ManyToManyField(through='courses.AWeekItem', to='courses.Item'),
        ),
        migrations.AddField(
            model_name='schoolcourse',
            name='items',
            field=models.ManyToManyField(through='courses.ASchoolCourseItem', to='courses.Item'),
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(through='courses.ACategoryCourse', to='courses.Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(through='courses.ACourseInstructor', to='courses.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(through='courses.ACourseResource', to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='acourseresource',
            name='id_course',
            field=models.ForeignKey(db_column='id_Course', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='acategorycourse',
            name='id_course',
            field=models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='acourseresource',
            unique_together={('id_resource', 'id_course')},
        ),
        migrations.AlterUniqueTogether(
            name='acategorycourse',
            unique_together={('id_category', 'id_course')},
        ),
    ]
