# Generated by Django 2.2.1 on 2019-05-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACategoryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'a_category_course',
            },
        ),
        migrations.CreateModel(
            name='ACourseInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'a_course_instructor',
            },
        ),
        migrations.CreateModel(
            name='ACourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'a_course_resource',
            },
        ),
        migrations.CreateModel(
            name='AWeekItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'a_week_item',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('categories', models.ManyToManyField(through='courses.ACategoryCourse', to='courses.Category')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('next', models.IntegerField(blank=True, null=True)),
                ('prev', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='MoocCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Course')),
            ],
            options={
                'db_table': 'mooc_course',
            },
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='NonSchool',
            fields=[
                ('instructor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Instructor')),
            ],
            options={
                'db_table': 'non_school',
            },
            bases=('courses.instructor',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('instructor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Instructor')),
                ('admissions_link', models.TextField(blank=True, null=True)),
                ('programs_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school',
            },
            bases=('courses.instructor',),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('items', models.ManyToManyField(through='courses.AWeekItem', to='courses.Item')),
                ('mooc_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.MoocCourse')),
            ],
            options={
                'db_table': 'week',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Item')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(through='courses.ACourseInstructor', to='courses.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(through='courses.ACourseResource', to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='aweekitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Item'),
        ),
        migrations.AddField(
            model_name='aweekitem',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Week'),
        ),
        migrations.CreateModel(
            name='ASchoolCourseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Item')),
            ],
            options={
                'db_table': 'a_school_course_item',
            },
        ),
        migrations.AddField(
            model_name='acourseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='acourseresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='acourseinstructor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='acourseinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Instructor'),
        ),
        migrations.AddField(
            model_name='acategorycourse',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Category'),
        ),
        migrations.AddField(
            model_name='acategorycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
        ),
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Course')),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('semester', models.SmallIntegerField(blank=True, null=True)),
                ('items', models.ManyToManyField(through='courses.ASchoolCourseItem', to='courses.Item')),
            ],
            options={
                'db_table': 'school_course',
            },
            bases=('courses.course',),
        ),
        migrations.AlterUniqueTogether(
            name='aweekitem',
            unique_together={('week', 'item')},
        ),
        migrations.AddField(
            model_name='aschoolcourseitem',
            name='school_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.SchoolCourse'),
        ),
        migrations.AlterUniqueTogether(
            name='acourseresource',
            unique_together={('resource', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='acourseinstructor',
            unique_together={('course', 'instructor')},
        ),
        migrations.AlterUniqueTogether(
            name='acategorycourse',
            unique_together={('category', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='aschoolcourseitem',
            unique_together={('school_course', 'item')},
        ),
    ]
