# Generated by Django 2.2.1 on 2019-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, to='courses.Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, to='courses.Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.Resource'),
        ),
    ]
