# Generated by Django 2.2.1 on 2019-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190513_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('CM', 'Cours magistral'), ('MC', 'Element Mooc'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques')], default='CM', max_length=2),
        ),
    ]
