# Generated by Django 2.2.4 on 2020-07-22 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_klazor.cell_set+', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'cell',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klazor.Folder')),
            ],
            options={
                'db_table': 'folder',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klazor.Folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_klazor.item_set+', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='AudioCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audio_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='FileCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Item')),
                ('file', models.FileField(null=True, upload_to='files')),
            ],
            options={
                'db_table': 'file',
            },
            bases=('klazor.item',),
        ),
        migrations.CreateModel(
            name='ImageCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('scale', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'image_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='MarkdownCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'markdown_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceInputCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
            ],
            options={
                'db_table': 'multiple_choice_input_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='NumericalInputCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('answer', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'numerical_input_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='OpenEndedInputCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'open_ended_input_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Item')),
            ],
            options={
                'db_table': 'sheet',
            },
            bases=('klazor.item',),
        ),
        migrations.CreateModel(
            name='VideoCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('scale', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'video_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='YoutubeCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('scale', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'youtube_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.AddField(
            model_name='item',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='klazor.Tag'),
        ),
        migrations.CreateModel(
            name='VideoCellSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('video_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klazor.VideoCell')),
            ],
            options={
                'db_table': 'video_cell_subtitle',
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, null=True)),
                ('is_true', models.BooleanField(default=False)),
                ('input_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.MultipleChoiceInputCell')),
            ],
            options={
                'db_table': 'proposition',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.Sheet'),
        ),
    ]
