# Generated by Django 2.2.1 on 2019-05-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('category_set', models.ManyToManyField(blank=True, to='klazor.Category')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sheet',
            },
        ),
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Content')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('audio', models.FileField(upload_to='audios')),
            ],
            options={
                'db_table': 'audio_content',
            },
            bases=('klazor.content',),
        ),
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Resource')),
                ('file', models.FileField(upload_to='resources/files')),
            ],
            options={
                'db_table': 'file_resource',
            },
            bases=('klazor.resource',),
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Content')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(upload_to='images')),
            ],
            options={
                'db_table': 'image_content',
            },
            bases=('klazor.content',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Sheet')),
                ('status', models.CharField(choices=[('UNSTARTED', 'Not started'), ('RUNNING', 'On going'), ('COMPLETED', 'Completed')], default='UNSTARTED', max_length=9)),
                ('next', models.IntegerField(blank=True, null=True)),
                ('prev', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
            },
            bases=('klazor.sheet',),
        ),
        migrations.CreateModel(
            name='LinkResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Resource')),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link_resource',
            },
            bases=('klazor.resource',),
        ),
        migrations.CreateModel(
            name='MarkdownContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Content')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'markdown_content',
            },
            bases=('klazor.content',),
        ),
        migrations.CreateModel(
            name='MoocCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Course')),
            ],
            options={
                'db_table': 'mooc_course',
            },
            bases=('klazor.course',),
        ),
        migrations.CreateModel(
            name='NotSchool',
            fields=[
                ('instructor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Instructor')),
            ],
            options={
                'db_table': 'not_school',
            },
            bases=('klazor.instructor',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('instructor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Instructor')),
                ('admissions_link', models.TextField(blank=True, null=True)),
                ('programs_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school',
            },
            bases=('klazor.instructor',),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Content')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.FileField(upload_to='videos')),
            ],
            options={
                'db_table': 'video_content',
            },
            bases=('klazor.content',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.Folder')),
                ('sheet_set', models.ManyToManyField(blank=True, to='klazor.Sheet')),
            ],
            options={
                'db_table': 'folder',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_set',
            field=models.ManyToManyField(blank=True, to='klazor.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='resource_set',
            field=models.ManyToManyField(blank=True, to='klazor.Resource'),
        ),
        migrations.AddField(
            model_name='content',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.Sheet'),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('item_set', models.ManyToManyField(to='klazor.Item')),
                ('mooc_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='klazor.MoocCourse')),
            ],
            options={
                'db_table': 'week',
            },
        ),
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Course')),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('semester', models.SmallIntegerField(blank=True, null=True)),
                ('item_set', models.ManyToManyField(to='klazor.Item')),
            ],
            options={
                'db_table': 'school_course',
            },
            bases=('klazor.course',),
        ),
    ]
