# Generated by Django 2.2.1 on 2019-05-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sequence']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='next',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='item',
            name='prev',
        ),
    ]
