# Generated by Django 2.2.3 on 2019-08-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='question',
            new_name='question_cell',
        ),
    ]
