# Generated by Django 2.2.3 on 2019-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
