# Generated by Django 2.2.4 on 2019-09-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCellSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('video_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klazor.VideoCell')),
            ],
            options={
                'db_table': 'video_cell_subtitle',
            },
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Item')),
                ('sheet_set', models.ManyToManyField(blank=True, to='klazor.Sheet')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('klazor.item',),
        ),
    ]
