# Generated by Django 2.2.4 on 2019-08-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='question_cell',
            new_name='input_cell',
        ),
        migrations.AlterModelTable(
            name='proposition',
            table='proposition',
        ),
    ]
