# Generated by Django 2.2.1 on 2019-05-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
