# Generated by Django 2.2.1 on 2019-05-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categories',
            new_name='category_set',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='instructors',
            new_name='instructor_set',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='resources',
            new_name='resource_set',
        ),
        migrations.RenameField(
            model_name='schoolcourse',
            old_name='items',
            new_name='item_set',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='items',
            new_name='item_set',
        ),
    ]
