# Generated by Django 2.2.3 on 2019-07-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0002_item_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='public',
            new_name='is_public',
        ),
    ]
