# Generated by Django 2.2.4 on 2020-07-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0002_auto_20200722_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sub_folder_set',
                to='klazor.Folder'
            ),
        ),
        migrations.DeleteModel(name='VideoCellSubtitle',),
    ]
