# Generated by Django 2.2.1 on 2019-05-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0002_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
