# Generated by Django 2.2.3 on 2019-08-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0002_auto_20190811_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='text',
            new_name='statement',
        ),
    ]
