# Generated by Django 2.2.4 on 2019-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0002_notebook_videocellsubtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocellsubtitle',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
