# Generated by Django 2.2.3 on 2019-07-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0003_auto_20190719_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
