# Generated by Django 2.2.4 on 2019-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0003_auto_20190929_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocellsubtitle',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
