# Generated by Django 2.2.1 on 2019-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0003_auto_20190524_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontent',
            name='width',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='width',
            field=models.FloatField(default=1),
        ),
    ]
