# Generated by Django 2.2.1 on 2019-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0004_auto_20190526_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecontent',
            old_name='width',
            new_name='display_width',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='width',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='display_width',
            field=models.FloatField(default=1),
        ),
    ]
