# Generated by Django 2.2.1 on 2019-05-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0004_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klazor.Folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='sheet_set',
            field=models.ManyToManyField(blank=True, to='klazor.Sheet'),
        ),
    ]
