# Generated by Django 2.2.4 on 2019-11-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0005_auto_20191111_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResourceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('course_resource_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.CourseResourceSet')),
            ],
        ),
    ]
