# Generated by Django 2.2.3 on 2019-07-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0005_auto_20190721_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
