# Generated by Django 2.2.4 on 2019-11-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0006_courseresource_courseresourceset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resource_set',
        ),
    ]
