# Generated by Django 2.2.1 on 2019-05-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0006_remove_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.Sheet'),
        ),
    ]
