# Generated by Django 2.2.1 on 2019-06-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0007_auto_20190530_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.Folder'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
