# Generated by Django 2.2.4 on 2019-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0007_remove_course_resource_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='course_resource_set',
        ),
        migrations.AddField(
            model_name='courseresourceset',
            name='resource_set',
            field=models.ManyToManyField(blank=True, to='klazor.CourseResource'),
        ),
    ]
