# Generated by Django 2.2.4 on 2019-11-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0008_auto_20191111_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klazor.Sheet'),
        ),
    ]
