# Generated by Django 2.2.1 on 2019-06-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0009_auto_20190622_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('subtopics', models.ManyToManyField(blank=True, to='klazor.Topic')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.RemoveField(
            model_name='filecourseresource',
            name='courseresource_ptr',
        ),
        migrations.RemoveField(
            model_name='linkcourseresource',
            name='courseresource_ptr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category_set',
        ),
        migrations.AlterField(
            model_name='course',
            name='resource_set',
            field=models.ManyToManyField(blank=True, to='klazor.FileItem'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CourseResource',
        ),
        migrations.DeleteModel(
            name='FileCourseResource',
        ),
        migrations.DeleteModel(
            name='LinkCourseResource',
        ),
        migrations.AddField(
            model_name='course',
            name='topic_set',
            field=models.ManyToManyField(blank=True, to='klazor.Topic'),
        ),
    ]
