# Generated by Django 2.2.1 on 2019-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0010_auto_20190626_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
