# Generated by Django 2.2.3 on 2019-07-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0010_auto_20190721_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotSchool',
        ),
    ]
