# Generated by Django 2.2.3 on 2019-07-21 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0011_delete_notschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('file', models.FileField(upload_to='files')),
            ],
            options={
                'db_table': 'file_cell',
            },
            bases=('klazor.cell',),
        ),
    ]
