# Generated by Django 2.2.3 on 2019-07-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0012_auto_20190722_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepart',
            name='level',
        ),
        migrations.AddField(
            model_name='coursepart',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klazor.CoursePart'),
        ),
    ]
