# Generated by Django 2.2.3 on 2019-07-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0013_auto_20190722_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepart',
            name='parent',
        ),
        migrations.AddField(
            model_name='coursepart',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
    ]
