# Generated by Django 2.2.3 on 2019-07-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0014_auto_20190722_0736'),
        ('klazor', '0012_filecell'),
    ]

    operations = [
    ]
