# Generated by Django 2.2.3 on 2019-07-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0015_merge_20190729_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('question', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
            },
            bases=('klazor.cell',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestionCell',
            fields=[
                ('questioncell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.QuestionCell')),
            ],
            options={
                'db_table': 'multiple_choice_question',
            },
            bases=('klazor.questioncell',),
        ),
        migrations.CreateModel(
            name='NumericalQuestionCell',
            fields=[
                ('questioncell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.QuestionCell')),
                ('answer', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'numerical_question',
            },
            bases=('klazor.questioncell',),
        ),
        migrations.CreateModel(
            name='OpenEndedQuestionCell',
            fields=[
                ('questioncell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.QuestionCell')),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'open_ended_question',
            },
            bases=('klazor.questioncell',),
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.MultipleChoiceQuestionCell')),
            ],
        ),
    ]
